spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ag04_prod
    username: ag04_prod_user
    password: hana
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
  sql:
    init:
      platform: mysql